set nocompatible " force setting to use features not compatible with vi
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'altercation/vim-colors-solarized'
Bundle 'vim-scripts/gnupg.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'vim-scripts/bufexplorer.zip'
Bundle 'L9'
Bundle 'FuzzyFinder'

filetype plugin indent on

syntax enable " enable syntax highlighting
set encoding=utf-8 " set encoding
set ttyfast " draw more to terminal
set showcmd " show incomplete commands
set hidden " enable hidden buffers by default
set wildmenu " show a list of possible completions when using <TAB>
set wildmode=list:longest " longest list
" set cursorline " a line where the cursor is
set ruler " row, column in bottom right
set laststatus=2 " always a status line
au BufWritePre * :set binary | set noeol " Save files in binary mode to be sure you save exactly what you see
au BufWritePost * :set nobinary | set eol " Reset to standard behavior after file is saved

if v:version >= 703
  set relativenumber " show relative line numbers
  set undofile " enables persistant undo between file reloads
endif

filetype plugin indent on

"" Whitespace
set nowrap " don't wrap lines
set tabstop=2 " set how many columns a tab i worth
set shiftwidth=2 " sets how many column will be shifted with << and >>
set expandtab " always expand tab to spaces
set backspace=indent,eol,start " enables backspacing through everything

"" Searching
set hlsearch " highlights search matches
set incsearch " start searching as soon as you type your first character
set ignorecase " ignore case when searching
set smartcase " do not ignore case when searching if at least one capital letter is used

if has('gui_running')
  set background=light
  colorscheme solarized
  set guioptions-=m " remove menu bar
  set guioptions-=T " remove toolbar
  set guioptions-=r " remove right scroll bar
  set guioptions-=L " remove left scroll bar
endif