filetype off

call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on

set nocompatible " force setting to use features not compatible with vi

syntax enable " enable syntax highlighting
set encoding=utf-8 " set encoding
set ttyfast " draw more to terminal
set showcmd " show incomplete commands
set hidden " enable hidden buffers by default
set wildmenu " show a list of possible completions when using <TAB>
set wildmode=list:longest " longest list
" set cursorline " a line where the cursor is
set ruler " row, column in bottom right
set laststatus=2 " always a status line

if v:version >= 703
  set relativenumber " show relative line numbers
  set undofile " enables persistant undo between file reloads
endif

filetype plugin indent on

"" Whitespace
set nowrap " don't wrap lines
set tabstop=2 " set how many columns a tab i worth
set shiftwidth=2 " sets how many column will be shifted with << and >>
set expandtab " always expand tab to spaces
set backspace=indent,eol,start " enables backspacing through everything

"" Searching
set hlsearch " highlights search matches
set incsearch " start searching as soon as you type your first character
set ignorecase " ignore case when searching
set smartcase " do not ignore case when searching if at least one capital letter is used

"" Unmap arrows
noremap <Left>  <NOP>
inoremap <Left>  <NOP>
noremap <Right> <NOP>
inoremap <Right> <NOP>
noremap <Up>    <NOP>
inoremap <Up>    <NOP>
noremap <Down>  <NOP>
inoremap <Down>  <NOP>

if has('gui_running')
  set background=light
  colorscheme solarized
  set guioptions-=m " remove menu bar
  set guioptions-=T " remove toolbar
  set guioptions-=r " remove right scroll bar
  set guioptions-=L " remove left scroll bar
endif

