#!/bin/sh

# Convert to utf-8.
iconv -f latin1 -t utf8 "$1" |\
# Remove headers
grep -v '"Datum","Transaktion","Kategori","Belopp",' |\
# Remove reservations
grep -v 'Reservation Kortköp' |\
# Replace "Kortköp"
sed 's/Kortköp/Visa/' |\
# Replace åäö
sed -e 's/[åä]/a/' -e 's/[ÅÄ]/A/' -e 's/ö/o/' -e 's/Ö/O/' |\
# Extract date
sed 's/"\([^"]*\)"/\1/' |\
# Extract title
sed 's/,"\([^"]*\)"/ \1/' |\
# Extract expenses
sed 's/,"",-\([0-9\.]*\),/\n  Expenses:Uncategorized  \1 kr\n  Assets:Bank:Checking\n/' |\
# Extract income
sed 's/,"",\([0-9\.]*\),/\n  Assets:Bank:Checking  \1 kr\n  Equity:Uncategorized\n/'

