export PATH="$HOME/bin:$PATH"
export EDITOR="/usr/bin/vim"
export DOTFILES="$HOME/.dotfiles"
export PRIVATESTORAGE="$HOME/.privatestorage"
export CREDENTIALS="$PRIVATESTORAGE/encrypted/credentials.gpg"
export LEDGER_FILE="$PRIVATESTORAGE/ledger/ledger"

if [ -e "$HOME/.zshenv.local" ]
then
  source "$HOME/.zshenv.local"
fi

