HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

setopt appendhistory extendedglob completealiases

bindkey -e

# zstyle :compinstall filename '/home/jonsa/.zshrc'

autoload -Uz compinit promptinit
compinit
promptinit

prompt walters

# keybindings
bindkey "^[OH" beginning-of-line
bindkey "^[OF" end-of-line
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word

alias ls="ls --color=auto"
alias genpass="openssl rand -base64 6"
alias editledger="vim $LEDGER_FILE"

function getpass() {
  if [ -x `which xclip` ]; then
    gpg -d $CREDENTIALS | prop print $1 password | xclip -selection primary
  else
    gpg -d $CREDENTIALS | prop print $1 password
  fi
}

function pullchanges() {
  echo "Pulling changes in dotfiles..."
  cd $DOTFILES
  git pull
  cd -
  echo "Pulling changes in private storage..."
  cd $PRIVATESTORAGE
  git pull
  cd -
}

