HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

setopt appendhistory extendedglob completealiases

bindkey -e

# zstyle :compinstall filename '/home/jonsa/.zshrc'

autoload -Uz compinit promptinit
compinit
promptinit

prompt walters

# keybindings
bindkey "^[OH" beginning-of-line
bindkey "^[OF" end-of-line
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word

alias genpass="openssl rand -base64 6"

function getpass() gpg -d $CREDENTIALS |\
  prop print $1 password |\
  xclip -selection primary

