zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'l:|=* r:|=*'
zstyle :compinstall filename '/home/jonas/.zshrc'

autoload -Uz compinit promptinit

compinit
promptinit
prompt walters

HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000

setopt appendhistory completealiases
unsetopt beep
bindkey -e

# keybindings
bindkey "^[OH" beginning-of-line
bindkey "^[OF" end-of-line
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word

alias ls="ls -l --color=auto"
alias untar="tar -xvf"
alias gitk="gitk --all"
alias lock="gnome-screensaver-command -l"
alias genpass="openssl rand -base64 6"
alias rehash="source ~/.zshenv && source ~/.zshrc && rehash"

function getpass() {
  if [ -x `which xclip` ]; then
    gpg -d $CREDENTIALS | prop print $1 password | xclip -selection primary
  else
    gpg -d $CREDENTIALS | prop print $1 password
  fi
}

function pullchanges() {
  echo "Pulling changes in dotfiles..."
  cd $DOTFILES
  git pull
  cd -
  echo "Pulling changes in private storage..."
  cd $PRIVATESTORAGE
  git pull
  cd -
}

if [ -e "$HOME/.zshrc.local" ]
then
  source "$HOME/.zshrc.local"
fi

